./smbd.1-new-base.cmd
./smbd.1-new-nebit3.cmd
./smbd.1-new-nebit5.cmd
./smbd.1-new-nebit6.cmd
./smbd.1-new-size16.cmd
./smbd.1-new-size64.cmd
#./smbd.1-new-line32.cmd
./smbd.1-LRU-assoc4.cmd
./smbd.1-LRU-assoc2.cmd
./smbd.1-LRU-assoc8.cmd
./smbd.1-LRU-size16.cmd
./smbd.1-LRU-size64.cmd
#./smbd.1-LRU-line32.cmd 
