./mail_t1-new-base.cmd
./mail_t1-new-nebit3.cmd
./mail_t1-new-nebit5.cmd
./mail_t1-new-nebit6.cmd
./mail_t1-new-size16.cmd
./mail_t1-new-size64.cmd
#./mail_t1-new-line32.cmd
./mail_t1-LRU-base.cmd
./mail_t1-LRU-assoc2.cmd
./mail_t1-LRU-assoc8.cmd
./mail_t1-LRU-size16.cmd
./mail_t1-LRU-size64.cmd
#./mail_t1-LRU-line32.cmd 
