./smbd.0-new-base.cmd
./smbd.0-new-nebit3.cmd
./smbd.0-new-nebit5.cmd
./smbd.0-new-nebit6.cmd
./smbd.0-new-size16.cmd
./smbd.0-new-size64.cmd
#./smbd.0-new-line32.cmd
./smbd.0-LRU-assoc4.cmd
./smbd.0-LRU-assoc2.cmd
./smbd.0-LRU-assoc8.cmd
./smbd.0-LRU-size16.cmd
./smbd.0-LRU-size64.cmd
#./smbd.0-LRU-line32.cmd 
