./mail_t2-new-base.cmd
./mail_t2-new-nebit3.cmd
./mail_t2-new-nebit5.cmd
./mail_t2-new-nebit6.cmd
./mail_t2-new-size16.cmd
./mail_t2-new-size64.cmd
#./mail_t2-new-line32.cmd
./mail_t2-LRU-base.cmd
./mail_t2-LRU-assoc2.cmd
./mail_t2-LRU-assoc8.cmd
./mail_t2-LRU-size16.cmd
./mail_t2-LRU-size64.cmd
#./mail_t2-LRU-line32.cmd 
